#!/bin/bash

function parseTag {
  frame_text=$(echo "$1" | grep "$2"| tr -d "[:cntrl:]")
  if [ ! -z "$frame_text" ]
  then
    frame_text=${frame_text:5}
  else
    frame_text=$3
  fi

  echo $frame_text
}

function process_file {
  filePathWithExtension=$1
  echo "Processing $filePathWithExtension"
  relativeFilePath=${filePathWithExtension:2}
  relativeFolderPath=$(dirname "$relativeFilePath")

  length=60

  tags=$(DEBUG=0 ./Id3TagReader.bash "$filePathWithExtension")
  trackTitle=$(parseTag "$tags" "TIT2" "$(basename "$filePathWithExtension" .mp3)")
  album=$(parseTag "$tags" "TALB" $relativeFolderPath)
  author=$(parseTag "$tags" "TPE1" "")

  addTrackStatement="    Soundtrack.Library.AddTrack(\"$relativeFilePath\", $length, \"$trackTitle\", \"$author\", \"$album\")"
  addTrackStatement="${addTrackStatement//\//\\\\}"
  echo "$addTrackStatement" >> MyTracks.lua
}

echo "-- This file is automatically generated" > MyTracks.lua
echo "-- Please do not edit it" >> MyTracks.lua
echo "function Soundtrack_LoadMyTracks()" >> MyTracks.lua

FILES=$(find . -name \*.mp3)
while IFS= read -r file; do
    process_file "$file"
done <<< "$FILES"

echo "end" >> MyTracks.lua
