#!/bin/sh

function process_file {
  echo "Processing $1"
}

echo "-- This file is automatically generated" > MyTracks.lua
echo "-- Please do not edit it" >> MyTracks.lua
echo "function Soundtrack_LoadMyTracks()" >> MyTracks.lua

FILES=$(find . -name \*.mp3)
while IFS= read -r file; do
    echo "$file"
done <<< "$FILES"

echo "end" >> MyTracks.lua
