#!/usr/bin/env python3
"""
GenerateMyLibrary.py — generate MyTracks.lua from a folder of MP3 files.

Scans a directory recursively for .mp3 files, reads their ID3 tags and
duration using mutagen, then writes a MyTracks.lua suitable for the
Soundtrack WoW addon.

Usage:
    python3 GenerateMyLibrary.py [--music PATH] [--output PATH]

Options:
    --music PATH    Path to the folder containing your MP3 files.
                    Default: SoundtrackMusic/ (sibling of the Soundtrack folder)
    --output PATH   Path to write MyTracks.lua.
                    Default: <music dir>/MyTracks.lua
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path

try:
    from mutagen.mp3 import MP3
    from mutagen.id3 import ID3
    from mutagen.id3._util import ID3NoHeaderError
except ImportError:
    sys.exit("ERROR: mutagen is required. Install it with: pip install mutagen")

DEFAULT_MUSIC_DIR = Path(__file__).parent.parent / "SoundtrackMusic"

def get_tag(tags, tag_id: str, fallback: str) -> str:
    try:
        value = str(tags[tag_id].text[0]).strip()
        return value if value else fallback
    except (KeyError, IndexError, AttributeError):
        return fallback


def escape_lua(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def process_file(mp3_path: Path, music_dir: Path):
    """Return (lua_track_path, duration_secs, title, artist, album)."""
    rel = mp3_path.relative_to(music_dir)
    # Build "Folder\\Subfolder\\TrackName" with no extension
    parts = list(rel.parts)
    parts[-1] = rel.stem
    lua_path = "\\".join(parts)

    audio = MP3(mp3_path)
    duration = int(audio.info.length)

    try:
        tags = ID3(mp3_path)
        title = get_tag(tags, "TIT2", mp3_path.stem)
        artist = get_tag(tags, "TPE1", "None")
        album = get_tag(tags, "TALB", "None")
    except ID3NoHeaderError:
        title = mp3_path.stem
        artist = "None"
        album = "None"

    return lua_path, duration, title, artist, album


LUA_HEADER = """\
-- This file is automatically generated
-- Please do not edit it
SMP3_PL_VERSION = "{version}"
function Soundtrack_LoadMyTracks()
   if SoundtrackAddon.db.profile.settings.MyTracksVersion == nil or SoundtrackAddon.db.profile.settings.MyTracksVersion ~= SMP3_PL_VERSION then
      SoundtrackAddon.db.profile.settings.MyTracksVersion = SMP3_PL_VERSION
      SoundtrackAddon.db.profile.settings.MyTracksVersionSame = false
   else
      SoundtrackAddon.db.profile.settings.MyTracksVersionSame = true
   end
"""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate MyTracks.lua for the Soundtrack WoW addon."
    )
    parser.add_argument(
        "--music",
        type=Path,
        default=DEFAULT_MUSIC_DIR,
        help="Path to the folder containing your MP3 files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Path to write MyTracks.lua (default: <music dir>/MyTracks.lua).",
    )
    args = parser.parse_args()

    music_dir: Path = args.music.resolve()
    output_path: Path = (args.output or music_dir / "MyTracks.lua").resolve()

    if not music_dir.is_dir():
        sys.exit(f"ERROR: Music directory not found: {music_dir}")

    mp3_files = sorted(music_dir.rglob("*.mp3"))
    if not mp3_files:
        print(f"WARNING: No MP3 files found in {music_dir}", file=sys.stderr)

    output_path.parent.mkdir(parents=True, exist_ok=True)

    version = datetime.now().strftime("%m/%d/%Y %H:%M:%S")

    with output_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write(LUA_HEADER.format(version=version))

        for mp3_path in mp3_files:
            try:
                lua_path, duration, title, artist, album = process_file(mp3_path, music_dir)
                print(f"{lua_path}: {duration}s, {title}, {artist}, {album}")
                out.write(
                    f'    Soundtrack.Library.AddTrack('
                    f'"{escape_lua(lua_path)}", {duration}, '
                    f'"{escape_lua(title)}", "{escape_lua(artist)}", "{escape_lua(album)}")\n'
                )
            except Exception as e:
                print(f"WARNING: skipping {mp3_path.name}: {e}", file=sys.stderr)

        out.write("end\n")

    print(f"\nGeneration complete! Written to {output_path}")


if __name__ == "__main__":
    main()
