#!/bin/sh

rm -rf '/mnt/c/World of Warcraft/_classic_era_/Interface/Addons/Soundtrack'
cp -Rv src/Soundtrack '/mnt/c/World of Warcraft/_classic_era_/Interface/Addons/'
cp -Rv src/SoundtrackMusic '/mnt/c/World of Warcraft/_classic_era_/Interface/Addons/'
