#!/bin/sh

#rm -rf '/Applications/World of Warcraft/_retail_/Interface/Addons/Soundtrack'
#rm -rf '/Applications/World of Warcraft/_retail_/Interface/Addons/SoundtrackMusic/LegacyLibraryGeneration'
rm -rf '/mnt/c/World of Warcraft/_retail_/Interface/Addons/Soundtrack'
rm -rf '/mnt/c/World of Warcraft/_retail_/Interface/Addons/SoundtrackMusic/LegacyLibraryGeneration'
./scripts/package SoundtrackTest.0.4.zip
./scripts/installFromZip SoundtrackTest.0.4.zip
