#!/bin/bash

GAME_FOLDER=$1
WOW_ROOT_PATH=$2

if [ -z "$GAME_FOLDER" ]; then
  echo "Provide game folder as first arg"
  exit 1
fi

if [ -z "$WOW_ROOT_PATH" ]; then
  WOW_ROOT_PATH="/mnt/c/World of Warcraft"
fi

echo "Game folder: $GAME_FOLDER"
echo "WoW root path: $WOW_ROOT_PATH"

# Extract version from TOC file
VERSION=$(grep "^## Version:" src/Soundtrack/Soundtrack-Mainline.toc | sed 's/^## Version: *//')

if [ -z "$VERSION" ]; then
  echo "Error: Could not find version in TOC file"
  exit 1
fi

ZIP_FILE="Soundtrack.$VERSION.zip"

rm -rf "$WOW_ROOT_PATH/$GAME_FOLDER/Interface/Addons/Soundtrack"
rm -rf "$WOW_ROOT_PATH/$GAME_FOLDER/Interface/Addons/SoundtrackMusic/LegacyLibraryGeneration"
./scripts/package
./scripts/installFromZip "$ZIP_FILE" "$GAME_FOLDER" "$WOW_ROOT_PATH"
