#!/bin/bash

GAME_FOLDER=$1

if [ -z "$GAME_FOLDER" ]; then
  echo "Provide game folder as first arg"
  exit 1
fi

rm -rf "/mnt/c/World of Warcraft/$GAME_FOLDER/Interface/Addons/Soundtrack"
rm -rf "/mnt/c/World of Warcraft/$GAME_FOLDER/Interface/Addons/SoundtrackMusic/LegacyLibraryGeneration"
./scripts/package SoundtrackTest.0.4.zip
./scripts/installFromZip SoundtrackTest.0.4.zip "$GAME_FOLDER"
